apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pb-stage-security
  namespace: policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: stage-clusters
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: policyset-stage-security
