apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stage-clusters
  namespace: policies
spec:
  clusterSets:
    - stage
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values: ["stage"]
