apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-policies-prod
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: acm-governance
spec:
  project: default
  source:
    repoURL: https://your.git/acm-gitops.git
    targetRevision: main
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
